name: Mac Push Test
on: [ push, pull_request ]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Get short commit hash
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Test mgpp
        run: |
          chmod +x gradlew
          ./gradlew :test

      - name: Build mgpp
        run: |
          chmod +x gradlew
          ./gradlew :main:shadowJar --info

      - name: Set Android SDK tools
        run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

      - name: Test Kotlin DSl
        run : |
          cd TestProjectKt
          chmod +x gradlew
          ./gradlew :deploy --info
          ./gradlew :antiAlias --info
          cd ..

      - name: Test Groovy DSl
        run : |
          cd TestProjectGroovy
          chmod +x gradlew
          ./gradlew :deploy --info
          ./gradlew :antiAlias --info
          cd ..

      - uses: actions/upload-artifact@v3
        with:
          name: mgpp-snapshot-build
          path: |
            main/build/libs/*.jar
            TestProjectGroovy/build/tmp/deploy/*.jar
            TestProjectKt/build/tmp/deploy/*.jar